Repository scoutapp/scout-apm-laravel, pull requests merged in 2019-09, with the labels that each got.

#7 Fix composer package name
  README.md
Labels: documentation

#4 Record view timing in instrumentation
  composer.json
  src/Events/ScoutViewEngineDecorator.php
  src/Facades/ScoutApm.php
  src/Providers/ScoutApmServiceProvider.php
Labels: enhancement

#12 Loosen runtime requirement of psr/log to ^1.0 to match scout-apm-php
  composer.json
Labels: bug

#15 Adding quality control to laravel binding library
  .gitignore
  .travis.yml
  README.md
  composer.json
  composer.lock
  phpcs.xml.dist
  phpunit.xml.dist
  psalm.xml.dist
  src/Commands/DownloadCoreAgent.php
  src/Database/QueryListener.php
  src/Events/RouteMatchedEvent.php
  src/Events/ScoutViewEngineDecorator.php
  src/Events/TemplateCreatedEvent.php
  src/Events/TemplateRenderedEvent.php
  src/Events/ViewComposer.php
  src/Events/ViewCreator.php
  src/Facades/ScoutApm.php
  src/Middleware/ActionInstrument.php
  src/Middleware/IgnoredEndpoints.php
  src/Middleware/MiddlewareInstrument.php
  src/Middleware/SendRequestToScout.php
  src/Providers/EventServiceProvider.php
  src/Providers/ScoutApmServiceProvider.php
  src/View/Engine/ScoutViewEngineDecorator.php
  tests/Unit/Database/QueryListenerTest.php
  tests/Unit/Facades/ScoutApmTest.php
  tests/Unit/Middleware/ActionInstrumentTest.php
  tests/Unit/Middleware/IgnoredEndpointsTest.php
  tests/Unit/Middleware/MiddlewareInstrumentTest.php
  tests/Unit/Middleware/SendRequestToScoutTest.php
  tests/Unit/Providers/ScoutApmServiceProviderTest.php
  tests/Unit/View/Engine/ScoutViewEngineDecoratorTest.php
  tests/bootstrap.php
Labels: enhancement

#16 Service provider fixes
  composer.json
  src/Providers/ScoutApmServiceProvider.php
Labels: bug

#18 Require 0.2.2 of php library
  composer.json
  composer.lock
Labels: enhancement

#19 Don't connect in Laravel boot()
  src/Middleware/SendRequestToScout.php
  src/Providers/ScoutApmServiceProvider.php
Labels: bug

#21 Remove Response type restrictions on middlewares
  src/Middleware/ActionInstrument.php
  src/Middleware/IgnoredEndpoints.php
  src/Middleware/MiddlewareInstrument.php
  src/Middleware/SendRequestToScout.php
Labels: bug

#22 Everyone loves badges
  README.md
Labels: documentation, enhancement
