Repository scoutapp/scout-apm-laravel, pull requests merged in 2020-05, with the labels that each got.

#56 Allow for Ramsey UUID V4
  composer.json
Labels: bug

#57 Dependencies & CI update
  .github/workflows/build.yml
  .travis.yml
  composer.lock
  tests/Unit/Providers/ScoutApmServiceProviderTest.php
Labels: enhancement

#59 Update scout-apm-php to ^4.4
  .github/workflows/build.yml
  composer.json
  composer.lock
Labels: dependencies, enhancement
